'''
In the world of Dota2, there are two parties: the Radiant and the Dire.

The Dota2 senate consists of senators coming from two parties. Now the Senate wants to decide on a change in the Dota2 game. The voting for this change is a round-based procedure. In each round, each senator can exercise one of the two rights:

Ban one senator's right: A senator can make another senator lose all his rights in this and all the following rounds.
Announce the victory: If this senator found the senators who still have rights to vote are all from the same party, he can announce the victory and decide on the change in the game.
Given a string senate representing each senator's party belonging. The character 'R' and 'D' represent the Radiant party and the Dire party. Then if there are n senators, the size of the given string will be n.

The round-based procedure starts from the first senator to the last senator in the given order. This procedure will last until the end of voting. All the senators who have lost their rights will be skipped during the procedure.

Suppose every senator is smart enough and will play the best strategy for his own party. Predict which party will finally announce the victory and change the Dota2 game. The output should be "Radiant" or "Dire".

 

Example 1:

Input: senate = "RD"
Output: "Radiant"
Explanation: 
The first senator comes from Radiant and he can just ban the next senator's right in round 1. 
And the second senator can't exercise any rights anymore since his right has been banned. 
And in round 2, the first senator can just announce the victory since he is the only guy in the senate who can vote.
Example 2:

Input: senate = "RDD"
Output: "Dire"
Explanation: 
The first senator comes from Radiant and he can just ban the next senator's right in round 1. 
And the second senator can't exercise any rights anymore since his right has been banned. 
And the third senator comes from Dire and he can ban the first senator's right in round 1. 
And in round 2, the third senator can just announce the victory since he is the only guy in the senate who can vote.
 

Constraints:

n == senate.length
1 <= n <= 104
senate[i] is either 'R' or 'D'.

Thoughts:

. anyone can eliminate any person from the other party irrespective of where they are order wise
    - so the question is who to eliminate? some kind of optimal elimination ? everyone plays to the optimal strategy
. basically last man standing wins
. makes sense for one person to eliminate one person from the other party all the time and the last man standing is the winner
    - technically if you know that count of the other party has decreased you might as well just stop early stop
    - makes sense to keep some kind of counter so that we can keep decrementing
. almost like simulation and the order matters
. strategy is to just eliminate the immediate next threat from the other party? yes because otherwise you are giving a chance 
'''
from collections import *
from sortedcontainers import *

class Solution:

    def get_counts_and_indices(self, senate):
        counts = defaultdict(int)
        indices = defaultdict(SortedList)

        for i, s in enumerate(senate):
            counts[s] += 1
            indices[s].add(i)

        return counts, indices

    def get_next_opponent_index(self, curr, i, indices):
        opponent = "D" if curr == "R" else "R"
        alive_opponent_indices = indices[opponent]
        next_i = alive_opponent_indices.bisect_right(i)
        
        if next_i == len(alive_opponent_indices):
            # the first one from circular
            return alive_opponent_indices[0]

        return alive_opponent_indices[next_i]

    def predictPartyVictory(self, senate: str) -> str:
        counts, indices = self.get_counts_and_indices(senate)
        alive = [True] * len(senate) # everyone has right to vote

        alive_indices = SortedList(list(range(len(senate))))

        round = 1
        while True:
            print(f"{round = }")
            to_remove = SortedList()

            for i in alive_indices:
                curr = senate[i]
                # as we are constantly modifying it 
                if i not in to_remove:
                    opp = "D" if curr == "R" else "R"

                    print(f"{counts = }, {i = }, {curr = }")

                    # early stop
                    if counts[opp] == 0:
                        print(f"{opp = } all dead ! so {curr = } WINS!")
                        return "Radiant" if curr == "R" else "Dire"

                    # do binary search for immediate next of i in the other camp
                    opp_i = self.get_next_opponent_index(curr, i, indices)
                    print(f"{opp_i = }")

                    # bookkeeping
                    indices[opp].discard(opp_i)
                    to_remove.add(opp_i)

                    counts[opp] -= 1
            
            # remove things from each sorted list at the end of the round since we cant modify the loop inplace
            for ri in to_remove:  
                alive_indices.discard(ri)

            round += 1

        return None # should never come here

    # much more efficient neetcode inspired code
    def predictPartyVictory_nc(self, senate: str) -> str:
        n = len(senate)

        # keep track of 2 queues one for all the indices of R's and another for all the indices of D's
        rq = deque()
        dq = deque()

        for i, s in enumerate(senate):
            if s == "R":
                rq.append(i)
            else:
                dq.append(i)

        # do the simulation until only one remains. The goal is for each candidate to remove the immediate one to the left of it 
        while rq and dq:
            '''
            . Basically we keep checking the head of both the queues and compare the starting elements.
            . Based on which ever one is shorter that means that they have the right to remove the first element from the other queue.
            . But once you remove it you need to still remain for the next round while also ensuring that you can can be removed by say the last opponent
            . To enable that circular nature we also remove the voter from its queue but add it back to its queue with an increased offset of the length
            . This way it survies to the next round and it can be also removed too
            '''
            if rq[0] < dq[0]:
                # we are removing it 
                dq.popleft()
                # adding it back 
                rq.append(rq.popleft() + n)
            else:
                # we are removing it 
                rq.popleft()
                # adding it back 
                dq.append(dq.popleft() + n)

        # whichever one remains is the winner
        if rq:
            return "Radiant"
        
        return "Dire"

if __name__ == "__main__":
    tests = [
        ("RDD", "Dire"),
        ("DRR", "Radiant"),
        ("RD", "Radiant"),
        ("DR", "Dire"),
        ("DDRRR", "Dire"),
        ("RRDDD", "Radiant"),
        ("RRRRRDRRDRDRRDRRDDRRDRDRDDDRRRRDRRRDDRDRDDDRRRDRDRRRDDDRRRDDRDRRDRDDDRRDDRRRDDDRDRRRRRRRRRDDRDRDDDDDRRDRRDRDRDDRDDRDRRDDRDRRRDDDDDDDRRDRRRRRDRRDRRDDDRDDRDRDRRDRRDDDDRRDDRDRDRRRRDDRDRRRRRDRRDDRRRDRDRRDDRDDDDDDDDDDDRRRRRRRRDRRRDDRDDRDDDDDRDDRRDRRDDRRDDRDDRDRRDRDDDDRDDRDRDRRDDDDDRDRDRRRRDRDRDRDDRDRRRRRDRRRRDDDDDDDRDRRDRRRDRDRRDRRDRDDRDRDRDRDDDDRRRDDDDDRDDRDRRDDRDDDDRRRRRDRRRDDRDDRDDRRRRRRRDRRRDDDDRRDDDDRDRRDDRRDDDRDRRRRRDDDRRRRRDRRRRRDRDRDRRRDRRRDDDDRRRRRDRRDDRDRRRDRDDDRDRDRRRDDDRDRDRDDDRRDDDDRDDRDRRRDDRDDDRRRDRRDRRDDRDDDDDRDDDRDDDDRDRRDRRDDRRDDRRRRDDRRRDRRDRDRDDDRRRDDDDRDDDDDDRDRRDRRRDDDRDDRDRRRDDDDDDRRDRRDDRDDRDRDRDDDRDDRRRDRDDRDRRRRRDDRDRRDRRDDDDDDRDRRRRDRRRRDDRRRDDRDRDDDDRRDRDDDRRDDDRDRDDRRDRRDDRRRDRRRDRRDRRRDDRRRDDDDRRDDDRRDRRDRDRRRRRDDRRRRRRDDRRDRRDDDDRRDRDDDDDDDRDDRDDDDDRDRRRDDRRRRRDDRDDDRRDDDDDRDRDDRRRRDDDRDDRDDRDRRDDRRRDRDDRDRDRDRDRRRDDDRDRDDRDDRRDRDRDDDRRDDDRDRRRDDRDDRRRRDRRRRRDRDRRRRRRDDDRRRDRRRRRDDDDRRDRDDRRDRRRDDDDDRDDRRDRDDRRRRDRRRDRRDDDRDRRRRRDDRRRDDDRRRDRRDRDDDDDDDRDRRDRDRDRDDDDDRDRRDDRRRDDDRDRRDDDDRRRDRRDDRDRRRRDRRDDDDDDDDRRRDDDDDDDRRDRDDDDDDDDRRDRRDDDRRDRRRDRDRDRRDDDDRDDRDDDRDRRDRRDRDDDRDRDRDDDRRRDDRDRRDDRRDRRRDRDDRDDDRRRRRRDDDDRDDDDDRRDRDDRDRRRDDRRRDRRDDDDRRDDRDDRDDRRDDRDRDDDRDDDRRRRDRDDDDRDDRDRDRDRDDRRRRRDRRDDDDDDDDDDRRRDRDDRRDRDRDDDDRRDDRDRDDDRDDDDDDRDDRRRDRDDRRDDDDRDRDDRRDRRRRDRRDRRDRDRDDRDRDRRRDRRDDDRDRDDDRDDRRRDDDDRDRDDRDRRRDDRRRRDRDDDDRRDRRDRDRDRRRDRDDRRDDRDDDRDDRDDRDDRDRRRRRRRDRRDRDRRDRRRRRRRDRDDRRRDRDRDRDDDRDDDDDRRDDRRDDDRRDRDRDRRRRDDRDDRRDRRRDRDDRDRRRDRRRRDDDRRRDRDDRDDDDDRDRDDDRRRDRDRDRRDRDDDDDDRRDRRRRDDDDRDRDRDDRRDRDRRDDRRDRDRDDDDDRDDRRDDRRRDRRRDDRRDRDRDRRDDRRDRDDRRRDDRDRDDDDRRDRRRDDDDRDRRRRDRDRDRDDRRDDRDRRDDDDDRDRRDDDRDDRDRDRDRDRDRRRDDRDDRRDDDDRRRDDRDRDRDRRDRRRRDDRDDRRRRDRRRDDDRRRRRRDRDRRRRDDDRDRDRDRRRRDDRRRRRDDRRDDDRRRRRDRRRDDRDRDDDRRRDRRRRDRDRDRDRDRDRRRDDRRRRDDDDRRDRRDRDRRRRDRDDRRDRDRRDDDRRRRRRDRRRRRRRDDRDDDDDRDRDDDDDDRRRRRRDRRRRDRDRRRDRDDDRDDDRRRDDDDRDDDDRDRDDDRDRDRDRDDDDRRDRDDRDRDDRRDDDRDDDRRRDDDRRDRDDRDRDRDRRRRRDRRDRRRRDDDDDRRRDDRDRRRDDDDRRRDDRDDRRDRRDDDDRRRRRDDRRRDRRDRRRDRRRRRDRRDDDDRRDRRDDRDDRRRRDDDDDRDDDDRRDDRRRDDDRDRRDDRRDRDDRDRRRRRRRDRDRDDRRRRRRDRRRRDRDDDDRRDRDDRRDRDRRRRRDDDRRRRRRRDDDRDDDDRDRRDDRDDDRRDRRRRRRDDRRDRDDDRDDDRRRDRDDDDDDDDDRDRDRDDRRRDDDDRRDRDRDRRDDRRDDDDDDDRDRRRDRRDRRRDDDRRRRDRDDRDDRDDDRRRDDDDDDRDDDRDRDDDRDRDRRDDRDDRDRDRRDDDRDDDDRDDDRRRDRRRRRDDDRDRRDRRRDDDRDRRDDRRDRDRRRRRRDDDRRRDDDRRRRDRRRRDRDDDRDRRRRRDRDRRRDDRRRDDRRRRDRDDDRRRRDRDRDRDRRDDRRDDDDRDDDDDRRRDRDRRRRRRRDRRRRRRDRDRDRRRDDRRRDDDDRDDRDRDRDRDRDRRDRDRDRDDRRRDRRDRDRRRDRDRRRRRRRRRDDDRDDRRDRDRRRRDRDDRRRRRRRRRRDDRDDRRRRDRDDRDRRDDDRDDRDRRDRDRRDDRDDRDRDRDRRDRDRRDDRDRDDDDDRDRRDRDDRDRDDRDRRDDDDDRRRDRDDRRRDRRRRDRDDRDRDDRRRRRDDRDRRDRDDDRRRRRRRRDRRRDDRDRDDDRDRDDDRDDDDRRDDDDRDDRRDDDDRRRDRRDDRDRDDDRDDDRDDDDDDDDRRRRRRDDRRRRRRRRDRDRDDDDDDDRDRRDDDDRDRRRRDRDRDRRRRRRDDDRDDRDRRRRDRRRDDRDRDDDDRRRRDDDRDRRDDDRRRRDRRDRDDDDDDRRRDDDRDDRRRRRRDRDRDDRDDDRDDDRRDDRDRDRDRDDDRDRDDDRDRDDDRDRRRRRDDDDRRDRRDDRDRDDDRDDRDRDRDDDDDRRRRDDRRRRDRDDDRDRRDRRRDRDDDDDDDDRRDDDDRDRRDDDDRDDRRDRRRRRDRRDRRDDRRDDDRRRRDDDRDRRRRRDDDRRRDDRRRDRDRDDDDRRRRDDRRDRDDDRRRDDDRDRRRDDDDDRRRDRDRDDDDDRDDDRRDRDRDRRRRRDDRDDRDDDRDDRRDRDDDDRRDDDRDDDRRRRDDDDRRDDDRDRDDDRDRRDRRDRDRRDRRDRDRDRDDRRRDDDRDDRRDDDRDDRRRDDDRRDRRRDDRDDDRDRRDDRDRRDDDRRDDRRRDRDDDRDDDDRDRDRDDDDDRDRDRRDRDRDRRRRRDRRRRRRRDDRRRDDRRRRRRRRDDDRRRRDRRRRDRDRRDDRDDRDDRRDDDRRDRRDDDDDDDDRDRDRRDDDDRDDDRRRRRDDDDDRDRDDDDDDDDRDRDDDRDRRRDDDDRRRDRDDRDRDDDRDDDDDDRRRRDDRDRDDRRDDDRDDDDRRDRDRDDDRRDDDDRRRDRDRDRRRDDDRDDRRDRRDDRRDRRDDRRDDRRRRDRRRDDRDDDDDDRRRDDDRDRRDRRDDDRRDRDDRDDRRDRRRDDRDRDDDRDDDDRDDDRDRRDDRDRDDDDDRRDDRRDDDDDDRRRRDRDDRDDRRRRDRRDDDRDDRRRRRRDDDRRRRDDDRDDRDDRRRDRRRRDRDDRDRDDRRRRDRDDRDDRDDDDDRRDRRRRRDRRRDRDDRDRRRRDRRDDDRDRDDDRDDDRDDDRRRRDRRDDRDDDRDDRDDRRRDDRDRDRRRRRDDRDRRDRDRRDDRRDRDRDDRRDRDDDRRRRDRDDRDDDDRRRRRDDDDDDRRDRDRRRDDRDDDRRDRDDDRRDRRDRDRDDDDDDDRRDDRRDDDRDRDRRDDDDRDRDDDRDRDRDRRDRRDRRRDRDRDRRRDRRDRDRRRDRRRRDDDDRDRDRRRRDRDRRRDRRRRDDRDDDRDDDDDDRDDDDRDRRDDDRDDDRRRDRDDDRRDDRDRDRRDRDRRRDRRRRRRDRRRDRDRDDRRRRDRRDRDDDDRRDDDDDDDDRDRDRRRRDRDDDDDRDDRRRDRDRDDDRDRRRRRDDDDDDRRDRRDRRDDDRRRRDRRRRDDDDDRDRRDRDRRDDRDRRRDRDDRRDDRDRRRRRRDRDDDRDDRDRRDDRDDRRRRRDDRRRDDDDRRDRDRDRRDDDDRDRRRRRRRDRDDDDDRDRRRDDRDRDDRRDDRDDDRRDRRRRRRDRRDDDRRRRRRRDRDDDRRRRDRDDDDDRRRDDDRRDRRDDDDRDDRRRDDRRRRDDRDRDDDDRDDRRDDDRDRRDDDRRDDDRDDRDDRDDDDRDRDRRRDDRDDRDRRDRRDDDDRDDRRRDDRDDRDDDRRRDDDDRDDRRDRDDDDRRRRDRDRDDDDRRDRRRRRDRDRRDRDRRRDDRRRDDRRRDDRRRDDDRRDRDDRDDDRDRDDRRDRRRRRDDDRRRDDRRDRRRDRDDRDRDDDRRDRRRRDRRDDRRRRDRDRRDRRDRDDRDDDDDRRDRRDRRDRRRDDRDRRDDDDRDDDDRDRRDDRDRRRDDRRDRRRDRDDDDDRRRRDDDRRRRDRRRRDRDDDDDDDDDRDDDDDDRDRRDRDDDDRRDDRRRDDDDDDDDDDRRDRRRDDDDRDDDDDRDDDRRRDRRDRRRDRRDDRRRDRDRRRRDRDDRRDDDRRDDDDRDRDRDDDRRDDDDDRDRDDRDDRRDDDRRRRRRRRRDRDDRDRDRRDDRRRDDDRRRRDRRRRRRDDDRRRRRRRRRRRRRDRDRDRRDDRDRDDRRRRDDRDDRDRDRRRDDDDRDRDDDRDRDRRDDDDRRDRDDDRRDRRRDRDRRRRDDRDDDDRDDRDDRDDRRDRDRDDRDRRDDRDDDDDRRDRDRDDRRDRDDDRDRDDDRDDRDRDRDRDDDDDDRRRDRDDDDRDRDRRDDRDDRRRRDRDRDRDRDDRRDDRRRDDRRRRDRRRDDRDDRRDDRDDRRRRDRRDRDDRDDDDDDDRRRRDDRDDRRRRRRRRRRDDRRDDDDRDDDDRDDDDRRDRRRDDRRDDDDRDDRRDDDRDRDRDDDDDRRRDRDDRRDDRDRDRDRRDDDDDDRRRDRDRDDDDRRDDRDDRRRDRDDDRRDDRDRRDDRRRRDDDDRRRRDDDRDDDDRDDRDDRDRDRDRDDDRRRRRDRRDRDRRDDDDDDDRRDRRDDRRDDDRDRDDRRDDRRDRRRRRRRDDDRRRRDDRRDRDRRDDDRRRRDRRRDRRRRRRRDRDDDDRRDRDDRRDRRDDDRRDDRRDRDRDRRRRDRRDDRDDDDDRDRRDDRDDRRDDRRDDDRDDRDDDRDDDRRDRDDDDDRDDRDDDDRDDRRRRDRDDDRRRRRRRDRRDRRDDDDDRRDRDDRDDRDDRDRRDDRDRRDDDDRRRDRRRRDDRDRRRRRRDRDRRDDRDDRRRDRDDRDDRRRRDDDDDDRRRDDRDRRDRDRRRDRDRRRRRDDDDDDRRDDRDRRDDDRDDDDDRDRRRDRDDDDRRDRDRRRDDDRRDDDRDRDRDRRRDRDRDRDRDRRDDDDRDDRDDDDDRRDDDDRRRDDDRDDDRRDRDDRDDDDDDRRRDDRDDRRDRRDDDDDDRRDRRRDDDDRRRDRDRDRDRRRRDDDDDDRDDDDDRDDRDDRDDDDDRRDDDRRDDDRRDDDDRDDDRDRRDRRDRDDRDRRRRRDDRDDRDRDDDDDDDRRDDDDRRRDRDRRDDRRRRRRDDRDDRRRDDDDRDDDDDDRDRDDRDDDRRDDRRRRDDDRRRRDRRDDRRRRRDDDDDDRDDDDRDRRRRDDDRRRRRDDDDDDRRRDRDDRRDRDDDDRDRRRDDDDDRDRRRRDDDRDDRDDDRRDRDRRRRDRDRDDDDDDDRDDDRRDDRDRRDDRRDDDDRDRRDDRRRDRDDDDDRRDRDRRRRDDRRRDDRDRRRDRDRRDDDRRDDRDRDRRRDDDRRRRDDRDRDDDDRDRRRRDDRRRRRRRDRDDDRRRRRRRRRRRDDRRRDRDRDRDDDRRRDRRRDRRDDRRRDDDRRRDRDRDDRRDDRDRDRRRDDDDDRRDDDDDRRRDRRDRDDDDRRDDRDDRDRDDDDDDDRRRDDRRDDRDRDDRDRRDDRRRRDRRDDDDDRDRRRDDRDDRDDDDRRRDRRRDRDRRRDRRDRRRRRRDRDDRDDRDRRRDDRDDDDDDDDRDRRRRDDRRRDRDRDRDRDRDRDDDDDDRRDRDDDDDDRDRDRDDRDDRDDRDDDRRDRDRDRRRRRDDDDDRRRRDRDRDDDRRDDDDDDDRDDDDDDRRRDDRDRRRDDDDRRDRRRDRRDDDDDRDDRRRDDDRRDRDDRDRRRRRDRRRRDDDRDDDRDRRRRRDDDRRDRDDDDRDRDRRRDDRDDRRRRDDDDRDRDDDRDRRDDRDRDRRRDRDDRRDDRRRRRDDDRRRDRDRDRDDDRRDDDDRDRRRDDRRDDRDDRDRRRRRRDRRDDRRDRDRDDDDDDRRDDDRDRRDRDRRRDRDDDRRDDDDDDDRDRRDDRRRRDDRRRDRDRRRRRRRDDDRDRDDDDRRRRDDDDRDRDRRDDRDRDRRDRDDRRRRDRRRDDRRRDDDRRRDRRDRRRDRDRDDRDRDDDDRDDRRRDRDRDDRDRDDRRRDRRDRRDRRDDDDRRRDDDDRDDDDDDDDDDRRDDDDRDDRDRRDRRDDDDRRRDDDDDDRDDRDDRDDRRDRRRRRRRRDRRDDDDDDRDDRDRRRRDRRDRRDDRRDRRDDRDDDDDDRDRRRRDRRDRDDRDDDRRDDDDRRRDRDRDRRRRRRDDDDRDDRRDRRRDDDRDDDDDDDRRDRDRRDRRRDRDDRDDDDDDRDRRRDRRRDDDDRRDRDRRRDDRRRRDDDRRDRDRDRRRDRDRDDRRDRRRRDDRDRRDDRDDDRDDRDDDDRDDRRDDRDRDDDDRRDRRRRDDDDRRDRRDRDRDRDRRRRRRDRDDRDDDDDRRDRDRDDDDDDRRRDDDDRRDRRRDRRRRRDRDDRDDDRRDDRRRRRRDDDDRRDDRDRDDDDRRRDDRRDRDDDRRRRDDDDRDDDRDDDRDRRRRDRDRDRDDRDRDDRDDRDRRRDRDRRDDRRRRRDDRDDDDDRDRRRDDRRRRDDRDDDDRDRRRRDRDRRRRRRRDRRDDRRDDDDDDDRRRRDRDDDDDRRRDRDRRDRDRRRDDRDRRRRRRRDRRRRRRRDDRDDRDDDDRRRDRDRRDDDDRRDRDDRDDDDRRRDDRDRRDDDDDDRRRRRRDRRRDDRRRRRRDDDRRRRRDDRDDRDRRDRRRRDRRDRDDRDRRDRRDRRDRDRDRDRRDRDDDRRRRRDDDRDDRDRDDRRDRRRRRRRDDRRRRRDRDDRRRRRRDRDRDRRDRDDRRDDDRRRDRDRDDDRDDDDDRRDRDRRDRRRRRRRDDDDRRRRDRRDDDRDRRDDDRDRRDDRRRRRDDRDDDDRRRDRRDDRDRRRRRRRDDRDDDDDRRDDDDDDDRRDDDDDDDDRDRDDDDDDDDRDRRDRRDDDDDDDDRDRRRDDRRDRDDRRDRDDDRRRRRRDRDDDRDRDDDRDRRRRDRRDDDDDDDDDDDRDDRDDDRDRRDRRDDRRRRDDDDRRRDRDDRDRRDDRRRRDRRDDRRRDDRRDDRRDDRDRDRDDDRDDRDDDDDRDRRRRDRDRRDDRDDRRRDRDDRDRDDDRRDRDDDRRRDDRRDRDRDDRDDDRRDRDDRDRRDRDDDDDRRRDDRDRRDRDDDDRDRRDRRDRDRRDDDDRDDDRDDDRRRDDDRRRRDDRRRDRRRDRRRRRDRDDDDDDRDRRDDDDRDDRRDRDRDDRRRRDRRDDDRDDDDRRRRRRRRDRDRDDRRDRRRDRDRDRDRRDDRRDDRDDDRDRRRDDDDDRRRRDDDDRDRRDDRRRRDRDRRDRDRDRRDRDDDDRRRRRRRDDRRDRDDRDDDRRRDRRDDDRRDRDRDDDDRDRDRRDDRRDDRDDRDDDDRDDDRDDDRDDRRDRDRRDDRDDDDRDDDDDDRRRDDDDDRDDRDRDDRDRDDRRDRRRDRRDDRRDRRDRDRDDDRDRRDDRRRDRDRRDDRRRDRRRDRRRDDRRRDDRRDRDDDRRRDDRRRRDRRDDDRDDRDRRDDDRDDDRRDDRDDDDRRRRDDDRDRDDRRRRRRDRRDRDDRRRDDRRRDRRDDRDRDDDDDRRRRDRRDRDRDDDRDRDDRDRRRDRDRDDDDDDRRRRDRRRRDDDDRDRDDRRRRRDRRRRRRDRRDDDDRRDRRRDRDRRDDRDDRDDDDRRRDRDDRDRRDRRDDDRRRDDRRDDRDDRRRDRRDRDDRDRDDRDDRDRDRRRRDDRRDDDRRDDRDRDRDDRRDRDRDDRDRRRRRRRRDDRRRDDRRRDRRDRRDDRRDRRRDRDDDDRRDRRDRDRDDDDDDDDRDRDDDDRDDDRDRRRDDRDRRRDDRRRRRDDDRDRDDDDRRDDRDDRDRDDRDRDRRRDDRRDRDRRRRRRDRDDRDRDRRDRDRDDRRRDDRRRRRRDRDDDDRDDDRRRDRRRRRDRDRRDDDRDRDRDDRRRDDRDRRDDRRDRDRRDDRRRRDRRRRDRDRDDDDRDDDDDRDDRRDDRDRRDRDDDDDRDRRDRRRDRDRRRRDRDDDRRRDRRDDRRRDDDRDRRRDDRDDRDRDDDRRDDDDRRRDRRDDDDDRDRRRDDRRDDRRDDDRRRDRRDDDRDRDDRRDDDRRDRDDRDDDRDDRDRRRDRRDDDRDRDDRRRDRDDRRDRDRDDDRRDDRDDRDRRRRDDRRDRDRDDRDRRRRRRDDRRDRDDDRRRRRRDDDRDDRRRDDDRRRDRDRRDDDDDRDDDRRDDRRDDRRDDDRRDRDDDDDDDDDRDRDDDDDDDRRDRDRDRRRRRRRDRDRRDRRRRDRRRDDDDRDDDDDDDRDRDRRDDDDDRDDDRRDDRDDDRRRDDDRDRDRDRDRRRRDDDDDRDDRRDRDRRRDRDRDRRRRRRDRDDDDRRRDDDRRDDRDDDDRDRDRDDRRDDDDRRDDDRDRRDDDDDDDRRRRDDRDDRDDDDRDDDDDRDDRRDDDRRRRRRRDDDDRDRDDRRDRDRRDRDRRDDRRDDDDRRRRRRDDDDDRRRDRRRDDDDDRRDRDRDRRRRRRRDDDRRDDRRDRDRDRRRDDRDRRDDDRRDRRDDRRDRRRRDRDRDRRRRRRRRRRDRDRRRRRDRDDRDDRDDRRRRDRRDRDDRDDDDRDDDRRDDRDDRRDDDDRDRRDRDDRRDDDRDDDDRDRDDDRRDRDRRRDRRDDDRDRRRRDDDRRDRDRRDDRDRRRRRRRDDDRRDRDDRDDDRDDRDDDDRRRRDDDDRRDRDRRRRRDRRRRDDDRRDDRDDRDRDRRRRRDDRRDRDDDDDDRDRDDRRDDRRRRRDDRDRRDRDDDDDDRDRRRDRDDRDDRRDRRRDRRRRRDDRDDRRDRDDRDDRDRRRDRDRDRDRDRRRRDRDRDRRDRDRRRDRDDRRDRRRRDDRRRDDRDRRDDDRRDRRRRDRDRDDDRDDDDDDRRDDDDDDDDRDDDRDDRDDDRRDRRDDDRDRRRDRDRRRRDDRRRDDRRDDRDRDDDDRRRRRRRDDRDDDDDDDRDDRRRDDRDDDRDRDRRDDRRRDRDRDDRDRDRDRRRRRRDRRDDRRDDDRRRDRRRDDDRRDRRRDRRRDRRRRDDDRDDDRDDRDDRRDRDRDRDDDDDRRDRRDDRDDRDRDRRRRRRRDDDDRDRDRRRRDRRRDDRRDRDDRDDRRRRRRRDDDDRRRRDRRRRDDDDDRDDDDDDDDDDDDDRRRRDRDDDDRRRDDRDDRDDRDDRRRRRRDDRDRDRRDRDDRRRRRDRDDDDDRRRDRRDRRRRDRRDDRDRDRDDRDDRDRRDRDDDDDRDDDRRDDDDDRDDDDRDRRRDDDDDRRDDRDRDDDRDRRDDDRDRDRDRRRDDRRDDRRRRDRDDDRRDDRDDDRRDDDRDDDDDRRDRRDDDRRRDDRRDRRRRDDDRRDDDDRDRRRRDRRRDRDRDDRDRRDDDDDRDRDDDRDRRRRDDDDDDRRRDRRRDRRDRRDRDRDDDDDDDRDDDRDRDRDDDRRRDRDRRDRDDRDRRRRRDRDRDDRRDDR", "Dire")
    ]

    s = Solution()

    for i, test in enumerate(tests):
        senate, expected = test
        print(f"Test {i}.> {senate = }, {expected = }")
        ans = s.predictPartyVictory(senate)
        assert ans == expected, f"{senate=}, {expected=}, {ans=}"
        print("-" * 60 + "\n")

